"""
defines the interface between various parts of the treerat project

TODO what is the overall structure of language components and how they interact? Kinda need to know now

TODO
protocol classes describe the interface, but should also implement the dumbest possible version of that interface.

protocols
* parser
* parser generator
* async core
* cli driver
* debugger
* visualizer
* linter
* lsp
* formatter

types
* match - parser output
* ast
* debug symbol?

exceptions
except Thing as e:
    raise Exception('msg') from e

* prefer typing.Protocol over ABC
    * https://docs.python.org/3/library/typing.html#typing.Protocol
    * with @runtime_checkable
* typing.NamedTuple
"""

from typing import  Generator, Iterable, NamedTuple, Protocol, runtime_checkable

class ParseError(SyntaxError):
    """raised if a parser fails on input."""
    # read up on how to pass details
    # https://docs.python.org/3/library/exceptions.html#SyntaxError

class EvalError(RuntimeError):
    """raised if an evaluator fails unexpectedly."""

class CompileError(EvalError):
    """raised if compile step fails unexpectedly."""

class EvalShutdown(EvalError):
    """The evaluator has reached a halt instruction."""

class BreakPoint(EvalError):
    """The evaluator has reached a breakpoint"""

type ast = tuple[str, *tuple[ast|str,...]]
class lexen(NamedTuple):
    style: str
    content: str

# TODO how do we handle continuable ParseErrors
# do we need batch/interactive modes for parsing, evaluation?

class match(NamedTuple):
    """
    representing a parsing match
    """
    start:int
    stop:int
    label:str = ''
    content:'tuple[match,...]' = ()
    def labelled(self) -> 'Generator[match]':
        if self.label:
            content = []
            for c in self.content:
                content.extend(c.labelled())
            yield self._replace(content=tuple(content))
        else:
            for c in self.content:
                yield from c.labelled()
    def ast(self, src:str) -> Generator[ast]:
        if self.label:
            content: list[ast] = []
            for c in self.content:
                content.extend(c.ast(src))
            if content:
                yield self.label, *content  # type: ignore[misc]
            else:
                yield self.label, src[self.start:self.stop]
        else:
            for c in self.content:
                yield from c.ast(src)

# TODO extract generic fmtTree
def fmtMatch(src, n:match, *, prefix:str='', next_p=''):
    label, start, stop, content = n
    out = [
        f"{prefix}{next_p}{label}{':' if label else ''}{src[start:stop]!r}"
    ]
    match next_p:
        case '├':
            prefix += '│'
        case '└':
            prefix += ' '
    if content:
        for c in content[:-1]:
            out.append(fmtMatch(src, c, prefix=prefix, next_p='├'))
        out.append(fmtMatch(src, content[-1], prefix=prefix, next_p='└'))
    return '\n'.join(out)

def fmtAst(a:ast|str, *, prefix='', next_p=''):
    match a:
        case str():
            return f"{prefix}{next_p}{a!r}"
        case _:
            out = [f"{prefix}{next_p}{a[0]}"]
            match next_p:
                case '├':
                    prefix += '│'
                case '└':
                    prefix += ' '
            if a[1:]:
                for c in a[1:-1]:
                    out.append(fmtAst(c, prefix=prefix, next_p='├'))
                out.append(fmtAst(a[-1], prefix=prefix, next_p='└'))
            return '\n'.join(out)

@runtime_checkable
class Parser(Protocol):
    def parse(self, text:str) -> match:
        raise ParseError('protocol not implemented')

    @property
    def kinds(self) -> set[str]:
        """return all ast node kinds which could be generated by this parser."""
        return set()

@runtime_checkable
class Lexer(Protocol):
    def lex(self, text:str) -> Iterable[lexen]:
        return [lexen('', text)]

@runtime_checkable
class Compiler(Protocol):
    def compile(self, a:Iterable[ast]) -> ast:
        return ('main', *a)

@runtime_checkable
class Evaluator(Protocol):
    """Evaluate an abstract syntax tree.

    This version is a treewalk evaluator where ast nodes are implemented as methods on the class.
    Methods receive unevalutated ast|str as arguments.
    """
    def __call__(self, ast:ast):
        fname, *args = ast
        return getattr(self, fname)(*args)

@runtime_checkable
class DebuggableEvaluator(Protocol):
    # TODO step, step_into, step_over, step_out
    def step(self):
        raise EvalError('proto not implemented')
    def step_into(self):
        raise EvalError('proto not implemented')
    def step_over(self):
        raise EvalError('proto not implemented')
    def step_out(self):
        raise EvalError('proto not implemented')
    def breakpoint(self, clear=False):
        raise EvalError('proto not implemented')


class Driver(Protocol):
    def start_core(self):
        pass
    def input(self):
        """get a line of user input."""
        return input('> ')
    def output(self, text):
        print(text)

